
import React, { useState } from 'react';
import PaymentModal from './PaymentModal';

interface NDADisplayProps {
  content: string;
  onReset: () => void;
  onSave?: () => void;
  accessLevel: 'locked' | 'watermarked' | 'full'; 
  onPaymentSuccess?: () => void;
}

declare global {
  interface Window {
    jspdf: any;
    docx: any;
  }
}

const NDADisplay: React.FC<NDADisplayProps> = ({ content, onReset, onSave, accessLevel, onPaymentSuccess }) => {
  const [justSaved, setJustSaved] = useState(false);
  const [showPayment, setShowPayment] = useState(false);
  const [isSavingToDrive, setIsSavingToDrive] = useState(false);

  const PRICE_INR = 200;

  const isLocked = accessLevel === 'locked';
  const isWatermarked = accessLevel === 'watermarked';
  const isFull = accessLevel === 'full';

  const handleCopy = () => {
    if (isLocked) {
      setShowPayment(true);
      return;
    }
    navigator.clipboard.writeText(content);
    alert('NDA copied to clipboard!');
  };

  const generatePDF = (): any => {
    const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Set font
    doc.setFont("times", "normal");
    doc.setFontSize(12);

    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);

    // Split text to fit page
    const splitText = doc.splitTextToSize(content, maxLineWidth);
    
    let cursorY = 20;

    // Add Title
    doc.setFontSize(16);
    doc.setFont("times", "bold");
    doc.text("NON-DISCLOSURE AGREEMENT", pageWidth / 2, cursorY, { align: "center" });
    cursorY += 15;

    // Add Content
    doc.setFontSize(11);
    doc.setFont("times", "normal");
    
    // Page handling loop
    let pageNumber = 1;
    
    // Function to add watermark
    const addWatermark = () => {
      if (isWatermarked) {
        doc.saveGraphicsState();
        doc.setGState(new doc.GState({ opacity: 0.1 }));
        doc.setFontSize(50);
        doc.setTextColor(150, 150, 150);
        // Add multiple watermarks for better coverage or one large one
        doc.text("HYRON AI", pageWidth / 2, pageHeight / 2, { align: "center", angle: 45, baseline: 'middle' });
        doc.restoreGraphicsState();
      }
    };

    addWatermark();

    splitText.forEach((line: string) => {
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        pageNumber++;
        addWatermark();
        cursorY = 20;
      }
      doc.text(line, margin, cursorY);
      cursorY += 6; // Line height
    });

    // Add footer to all pages
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by HYRON AI - Confidential', margin, pageHeight - 10);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: "right" });
    }
    return doc;
  }

  const generateDOCX = () => {
    if (!window.docx) return;
    const { Document, Packer, Paragraph, TextRun, HeadingLevel, AlignmentType, Header, Footer } = window.docx;

    const sections = [{
      properties: {},
      children: [
        new Paragraph({
          text: "NON-DISCLOSURE AGREEMENT",
          heading: HeadingLevel.HEADING_1,
          alignment: AlignmentType.CENTER,
          spacing: { after: 300 },
        }),
        ...content.split('\n').map((line: string) => 
          new Paragraph({
            children: [new TextRun(line)],
            spacing: { after: 120 },
          })
        )
      ],
    }];

    // If watermarked, add a header stating it's a sample
    if (isWatermarked) {
       (sections[0] as any).headers = {
        default: new Header({
            children: [
                new Paragraph({
                    children: [
                        new TextRun({
                            text: "HYRON AI - SAMPLE DOCUMENT",
                            bold: true,
                            color: "CCCCCC",
                            size: 24,
                        }),
                    ],
                    alignment: AlignmentType.CENTER,
                }),
            ],
        }),
       };
    }

    const doc = new Document({
      sections: sections,
    });

    Packer.toBlob(doc).then((blob: Blob) => {
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = isWatermarked ? "HYRON_NDA_Sample.docx" : "HYRON_NDA.docx";
      a.click();
      window.URL.revokeObjectURL(url);
    });
  };

  const handleDownloadPDF = () => {
    if (isLocked) {
      setShowPayment(true);
      return;
    }
    const doc = generatePDF();
    doc.save(isWatermarked ? "HYRON_NDA_Sample.pdf" : "HYRON_NDA_Legal_Document.pdf");
  };

  const handleDownloadDOCX = () => {
    if (isLocked) {
      setShowPayment(true);
      return;
    }
    generateDOCX();
  };

  const handleSaveToDrive = () => {
     if (!isFull) {
      setShowPayment(true);
      return;
    }
    
    setIsSavingToDrive(true);
    setTimeout(() => {
      setIsSavingToDrive(false);
      alert("Successfully saved 'HYRON_NDA_Legal_Document.pdf' to your Google Drive.");
    }, 2000);
  };

  const handleSave = () => {
    if (onSave) {
      onSave();
      setJustSaved(true);
      setTimeout(() => setJustSaved(false), 3000);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto flex flex-col h-full animate-fadeIn relative">
      
      {showPayment && onPaymentSuccess && (
        <PaymentModal 
          amount={PRICE_INR} 
          description={isWatermarked ? "Upgrade to remove watermark" : "Unlock Document"}
          onClose={() => setShowPayment(false)}
          onSuccess={() => {
            onPaymentSuccess();
            setShowPayment(false);
          }}
        />
      )}

      {/* Action Bar */}
      <div className="flex flex-col xl:flex-row justify-between items-center mb-6 gap-4">
        <div className="text-center xl:text-left">
           <h2 className="text-2xl font-bold text-white tracking-tight">Your Generated NDA</h2>
           <p className="text-slate-400 text-sm">
             {isFull ? "Professional License. All formats unlocked." : 
              isWatermarked ? "Sample Mode. PDF & DOCX Watermarked. Upgrade for clean copy." : 
              "Preview Mode. Unlock to download."}
           </p>
        </div>
        <div className="flex flex-wrap justify-center gap-3">
          <button 
            onClick={onReset}
            className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300 hover:bg-slate-700 text-sm font-medium transition-colors"
          >
            New Draft
          </button>
          
          {onSave && (
            <button 
              onClick={handleSave}
              disabled={justSaved}
              className={`px-4 py-2 rounded-lg border text-sm font-medium transition-all flex items-center ${justSaved ? 'bg-green-500/20 border-green-500 text-green-400' : 'bg-slate-800 text-emerald-400 border-emerald-500/30 hover:bg-slate-700 hover:border-emerald-500/50'}`}
            >
              {justSaved ? "Saved!" : "Save to Account"}
            </button>
          )}

          {!isLocked && (
             <button 
                onClick={handleCopy}
                className="px-4 py-2 rounded-lg bg-slate-800 text-blue-400 border border-blue-500/30 hover:bg-slate-700 text-sm font-medium transition-all flex items-center"
              >
                Copy Text
              </button>
          )}

          {!isLocked && (
            <>
              {/* DOCX Button */}
              <button
                onClick={handleDownloadDOCX}
                className={`px-4 py-2 rounded-lg text-sm font-medium transition-all flex items-center border ${isFull ? 'bg-slate-800 text-white border-slate-600 hover:bg-slate-700' : 'bg-slate-900 text-slate-400 border-slate-700 hover:text-slate-300'}`}
                title="Download Word Doc"
              >
                <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 12h6m-6 4h6m2 5H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                </svg>
                {isFull ? "DOCX" : "DOCX (Sample)"}
              </button>

              <button 
                onClick={handleDownloadPDF}
                className="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-500 shadow-lg shadow-blue-500/20 text-sm font-medium transition-all flex items-center"
              >
                Download PDF
              </button>
            </>
          )}

          {isFull && (
             <button 
                onClick={handleSaveToDrive}
                disabled={isSavingToDrive}
                className="px-4 py-2 rounded-lg bg-slate-800 text-white border border-slate-600 hover:bg-slate-700 text-sm font-medium transition-all flex items-center"
             >
                {isSavingToDrive ? 'Saving...' : 'Drive'}
             </button>
          )}

          {isLocked && (
            <button 
              onClick={() => setShowPayment(true)}
              className="px-6 py-2 rounded-lg bg-gradient-to-r from-amber-500 to-orange-600 text-white shadow-lg text-sm font-bold transition-all flex items-center animate-pulse"
            >
              <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
              </svg>
              Unlock (₹{PRICE_INR})
            </button>
          )}
        </div>
      </div>

      {/* Document View */}
      <div className="relative flex-grow rounded-sm shadow-2xl overflow-hidden bg-white text-slate-900 border-4 border-slate-800/50 min-h-[600px]">
        
        {/* Overlay for LOCKED State */}
        {isLocked && (
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-white/10 backdrop-blur-[2px]">
             <div className="bg-slate-900/90 p-8 rounded-2xl shadow-2xl text-center max-w-sm border border-slate-700">
               <div className="w-16 h-16 bg-amber-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                 <svg className="w-8 h-8 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                 </svg>
               </div>
               <h3 className="text-xl font-bold text-white mb-2">Limit Reached</h3>
               <p className="text-slate-400 text-sm mb-6">
                 Your plan limit has been reached. Upgrade to generate more professional documents.
               </p>
               <button 
                 onClick={() => setShowPayment(true)}
                 className="w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold transition-all shadow-lg shadow-blue-500/25"
               >
                 Pay ₹{PRICE_INR} to Unlock
               </button>
             </div>
          </div>
        )}

        {/* Paper Effect Top */}
        <div className="absolute top-0 left-0 right-0 h-16 bg-gradient-to-b from-gray-100 to-transparent pointer-events-none z-10"></div>
        
        <div className={`h-[600px] overflow-y-auto document-scroll p-8 md:p-12 font-serif text-sm md:text-base leading-relaxed whitespace-pre-wrap select-text ${isLocked ? 'blur-content overflow-hidden' : ''}`}>
            {content}
        </div>

        {/* Paper Effect Bottom */}
        <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-gray-100 to-transparent pointer-events-none z-10"></div>
      </div>

      <div className="mt-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-start space-x-3">
         <svg className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
           <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
         </svg>
         <div>
            <h4 className="text-sm font-semibold text-amber-500 mb-1">Legal Disclaimer</h4>
            <p className="text-xs text-amber-200/80 leading-relaxed">
              This document is generated by AI under the <strong>Indian Contract Act, 1872</strong>. 
              It does not constitute legal advice. Review with a qualified advocate before signing.
            </p>
         </div>
      </div>

    </div>
  );
};

export default NDADisplay;
