
import React, { useState } from 'react';
import PaymentModal from './PaymentModal';

interface NDADisplayProps {
  content: string;
  onReset: () => void;
  onSave?: () => void;
  accessLevel: 'locked' | 'view-only' | 'full'; // 'locked' = blur, 'view-only' = see text no pdf, 'full' = everything
  onPaymentSuccess?: () => void;
}

// Add type definition for jspdf
declare global {
  interface Window {
    jspdf: any;
  }
}

const NDADisplay: React.FC<NDADisplayProps> = ({ content, onReset, onSave, accessLevel, onPaymentSuccess }) => {
  const [justSaved, setJustSaved] = useState(false);
  const [showPayment, setShowPayment] = useState(false);
  const [isSavingToDrive, setIsSavingToDrive] = useState(false);

  const PRICE_INR = 200;

  const isLocked = accessLevel === 'locked';
  const isViewOnly = accessLevel === 'view-only';
  const isFull = accessLevel === 'full';

  const handleCopy = () => {
    if (isLocked) {
      setShowPayment(true);
      return;
    }
    navigator.clipboard.writeText(content);
    alert('NDA copied to clipboard!');
  };

  const generatePDF = (): any => {
     const { jsPDF } = window.jspdf;
    const doc = new jsPDF();
    
    // Set font
    doc.setFont("times", "normal");
    doc.setFontSize(12);

    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    const maxLineWidth = pageWidth - (margin * 2);

    // Split text to fit page
    const splitText = doc.splitTextToSize(content, maxLineWidth);
    
    let cursorY = 20;

    // Add Title
    doc.setFontSize(16);
    doc.setFont("times", "bold");
    doc.text("NON-DISCLOSURE AGREEMENT", pageWidth / 2, cursorY, { align: "center" });
    cursorY += 15;

    // Add Content
    doc.setFontSize(11);
    doc.setFont("times", "normal");
    
    // Page handling loop
    const pageHeight = doc.internal.pageSize.getHeight();
    
    splitText.forEach((line: string) => {
      if (cursorY > pageHeight - 20) {
        doc.addPage();
        cursorY = 20;
      }
      doc.text(line, margin, cursorY);
      cursorY += 6; // Line height
    });

    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    for (let i = 1; i <= pageCount; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text('Generated by HYRON AI - Confidential', margin, pageHeight - 10);
        doc.text(`Page ${i} of ${pageCount}`, pageWidth - margin, pageHeight - 10, { align: "right" });
    }
    return doc;
  }

  const handleDownload = () => {
    if (!isFull) {
      // If view-only, they still need to pay for PDF
      setShowPayment(true);
      return;
    }

    const doc = generatePDF();
    doc.save("HYRON_NDA_Legal_Document.pdf");
  };

  const handleSaveToDrive = () => {
     if (!isFull) {
      setShowPayment(true);
      return;
    }
    
    setIsSavingToDrive(true);
    
    // Simulate API call to Google Drive
    setTimeout(() => {
      setIsSavingToDrive(false);
      alert("Successfully saved 'HYRON_NDA_Legal_Document.pdf' to your Google Drive.");
    }, 2000);
  };

  const handleSave = () => {
    if (onSave) {
      onSave();
      setJustSaved(true);
      setTimeout(() => setJustSaved(false), 3000);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto flex flex-col h-full animate-fadeIn relative">
      
      {showPayment && onPaymentSuccess && (
        <PaymentModal 
          amount={PRICE_INR} 
          description={isViewOnly ? "Upgrade to download PDF & Commercial Use" : "Unlock Document"}
          onClose={() => setShowPayment(false)}
          onSuccess={() => {
            onPaymentSuccess();
            setShowPayment(false);
          }}
        />
      )}

      {/* Action Bar */}
      <div className="flex flex-col xl:flex-row justify-between items-center mb-6 gap-4">
        <div className="text-center xl:text-left">
           <h2 className="text-2xl font-bold text-white tracking-tight">Your Generated NDA</h2>
           <p className="text-slate-400 text-sm">
             {isFull ? "Document Unlocked. Ready for download." : 
              isViewOnly ? "Free View Access. Text Copy Enabled." : 
              "Preview Mode. Unlock to download PDF."}
           </p>
        </div>
        <div className="flex flex-wrap justify-center gap-3">
          <button 
            onClick={onReset}
            className="px-4 py-2 rounded-lg bg-slate-800 text-slate-300 hover:bg-slate-700 text-sm font-medium transition-colors"
          >
            New Draft
          </button>
          
          {onSave && (
            <button 
              onClick={handleSave}
              disabled={justSaved}
              className={`px-4 py-2 rounded-lg border text-sm font-medium transition-all flex items-center ${justSaved ? 'bg-green-500/20 border-green-500 text-green-400' : 'bg-slate-800 text-emerald-400 border-emerald-500/30 hover:bg-slate-700 hover:border-emerald-500/50'}`}
            >
              {justSaved ? "Saved!" : "Save to Account"}
            </button>
          )}

          {/* Copy Button (Available if not locked) */}
          {!isLocked && (
             <button 
                onClick={handleCopy}
                className="px-4 py-2 rounded-lg bg-slate-800 text-blue-400 border border-blue-500/30 hover:bg-slate-700 text-sm font-medium transition-all flex items-center"
              >
                Copy Text
              </button>
          )}

          {isFull ? (
            <>
               {/* Google Drive Button */}
              <button 
                onClick={handleSaveToDrive}
                disabled={isSavingToDrive}
                className="px-4 py-2 rounded-lg bg-slate-800 text-white border border-slate-600 hover:bg-slate-700 text-sm font-medium transition-all flex items-center"
              >
                {isSavingToDrive ? (
                  <span className="flex items-center">
                    <svg className="animate-spin -ml-1 mr-2 h-4 w-4 text-white" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24">
                      <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4"></circle>
                      <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                    </svg>
                    Saving...
                  </span>
                ) : (
                  <>
                    <svg className="w-4 h-4 mr-2" viewBox="0 0 87.3 78" xmlns="http://www.w3.org/2000/svg">
                      <path d="m6.6 66.85 3.85 6.65c.8 1.4 1.95 2.5 3.3 3.3l13.75-23.8h-27.5c0 1.55.4 3.1 1.2 4.5z" fill="#0066da"/>
                      <path d="m43.65 25-13.75-23.8c-1.35.8-2.5 1.9-3.3 3.3l-25.4 44a9.06 9.06 0 0 0 -1.2 4.5h27.5z" fill="#00ac47"/>
                      <path d="m73.55 76.8c1.35-.8 2.5-1.9 3.3-3.3l1.6-2.75 7.65-13.25c.8-1.4 1.2-2.95 1.2-4.5h-27.502l5.852 11.5z" fill="#ea4335"/>
                      <path d="m43.65 25 13.75 23.8 13.75-23.8h-27.5z" fill="#00832d"/>
                      <path d="m59.8 53h-27.5l13.75 23.8z" fill="#2684fc"/>
                      <path d="m73.4 26.5-12.7-22c-.8-1.4-1.95-2.5-3.3-3.3h-13.75l13.75 23.8z" fill="#ffba00"/>
                    </svg>
                    Save to Drive
                  </>
                )}
              </button>

              <button 
                onClick={handleDownload}
                className="px-4 py-2 rounded-lg bg-blue-600 text-white hover:bg-blue-500 shadow-lg shadow-blue-500/20 text-sm font-medium transition-all flex items-center"
              >
                Download PDF
              </button>
            </>
          ) : (
            <button 
              onClick={() => setShowPayment(true)}
              className={`px-6 py-2 rounded-lg bg-gradient-to-r ${isViewOnly ? 'from-slate-700 to-slate-800 border border-amber-500/50 text-amber-500' : 'from-amber-500 to-orange-600 text-white'} shadow-lg text-sm font-bold transition-all flex items-center ${isLocked ? 'animate-pulse' : 'hover:bg-slate-700'}`}
            >
              <svg className="w-4 h-4 mr-2" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                {isViewOnly ? (
                     <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 10v6m0 0l-3-3m3 3l3-3m2 8H7a2 2 0 01-2-2V5a2 2 0 012-2h5.586a1 1 0 01.707.293l5.414 5.414a1 1 0 01.293.707V19a2 2 0 01-2 2z" />
                ) : (
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                )}
              </svg>
              {isViewOnly ? "Get PDF (₹200)" : `Unlock (₹${PRICE_INR})`}
            </button>
          )}
        </div>
      </div>

      {/* Document View */}
      <div className="relative flex-grow rounded-sm shadow-2xl overflow-hidden bg-white text-slate-900 border-4 border-slate-800/50 min-h-[600px]">
        
        {/* Overlay for LOCKED State */}
        {isLocked && (
          <div className="absolute inset-0 z-20 flex flex-col items-center justify-center bg-white/10 backdrop-blur-[2px]">
             <div className="bg-slate-900/90 p-8 rounded-2xl shadow-2xl text-center max-w-sm border border-slate-700">
               <div className="w-16 h-16 bg-amber-500/20 rounded-full flex items-center justify-center mx-auto mb-4">
                 <svg className="w-8 h-8 text-amber-500" fill="none" viewBox="0 0 24 24" stroke="currentColor">
                   <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 15v2m-6 4h12a2 2 0 002-2v-6a2 2 0 00-2-2H6a2 2 0 00-2 2v6a2 2 0 002 2zm10-10V7a4 4 0 00-8 0v4h8z" />
                 </svg>
               </div>
               <h3 className="text-xl font-bold text-white mb-2">Free Limit Reached</h3>
               <p className="text-slate-400 text-sm mb-6">
                 You have used your 1 free monthly NDA. Pay a small fee to unlock this document and download the PDF.
               </p>
               <button 
                 onClick={() => setShowPayment(true)}
                 className="w-full py-3 rounded-xl bg-blue-600 hover:bg-blue-500 text-white font-bold transition-all shadow-lg shadow-blue-500/25"
               >
                 Pay ₹{PRICE_INR} to Unlock
               </button>
             </div>
          </div>
        )}

        {/* Paper Effect Top */}
        <div className="absolute top-0 left-0 right-0 h-16 bg-gradient-to-b from-gray-100 to-transparent pointer-events-none z-10"></div>
        
        <div className={`h-[600px] overflow-y-auto document-scroll p-8 md:p-12 font-serif text-sm md:text-base leading-relaxed whitespace-pre-wrap select-text ${isLocked ? 'blur-content overflow-hidden' : ''}`}>
            {content}
        </div>

        {/* Paper Effect Bottom */}
        <div className="absolute bottom-0 left-0 right-0 h-16 bg-gradient-to-t from-gray-100 to-transparent pointer-events-none z-10"></div>
      </div>

      {/* Disclaimer Section below document */}
      <div className="mt-6 p-4 bg-amber-500/10 border border-amber-500/20 rounded-lg flex items-start space-x-3">
         <svg className="w-5 h-5 text-amber-500 flex-shrink-0 mt-0.5" fill="none" viewBox="0 0 24 24" stroke="currentColor">
           <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M12 9v2m0 4h.01m-6.938 4h13.856c1.54 0 2.502-1.667 1.732-3L13.732 4c-.77-1.333-2.694-1.333-3.464 0L3.34 16c-.77 1.333.192 3 1.732 3z" />
         </svg>
         <div>
            <h4 className="text-sm font-semibold text-amber-500 mb-1">Legal Disclaimer (Indian Context)</h4>
            <p className="text-xs text-amber-200/80 leading-relaxed">
              HYRON AI is an automated tool. While this document is drafted to align with the <strong>Indian Contract Act, 1872</strong>, it is generated by AI and may contain errors. 
              This document <strong>does not constitute legal advice</strong>. We strongly recommend reviewing this document with a qualified advocate in India before signing.
            </p>
         </div>
      </div>

    </div>
  );
};

export default NDADisplay;
